### ISSUE TITLE
Crash with Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons ?

### ISSUE THREAD

**Issue by Thysium** [Majrusz/MajruszsProgressiveDifficultyMod#141] opened 2023-05-02 15:47 UTC
Hello, is this a compatibility problem?

https://pastebin.com/KBHedTMY

**Comment by Majrusz** [comment] 2023-06-03 07:48
Hi, thanks for the report. It is a duplicate of https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/142 so I will close this one

**Closed as completed by Majrusz** 2023-06-03 07:48 UTC
Labels: bug, 1.18.X, 1.19.X
