### ISSUE TITLE
forge server (1.19.2) undead army wave crash

### ISSUE THREAD

**Issue by uchikun** [Majrusz/MajruszsProgressiveDifficultyMod#144] opened 2023-05-31 00:07 UTC
[latest.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/11607274/latest.log)
not sure what is causing the crash :(

**Comment by Majrusz** [comment] 2023-05-31 08:25
Hi, thanks for the report, but it is a duplicate of https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/142

**Closed as completed by Majrusz** 2023-05-31 08:25 UTC
Labels: bug, duplicate, 1.18.X, 1.19.X
