### ISSUE TITLE
[1.18.2] Off-hand behavior is odd with other mods

### ISSUE THREAD

**Issue by Cixon** [Majrusz/MajruszsProgressiveDifficultyMod#148] opened 2023-06-04 07:12 UTC
Attacked a Lion from Untamed Wilds mod and game died.
Mod: https://www.curseforge.com/minecraft/mc-mods/untamedwilds

Log (line 2,773):
[latest.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/11645059/latest.log)

Crash:
[crash-2023-06-04_02.09.40-client.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/11645060/crash-2023-06-04_02.09.40-client.txt)

**Comment by Cixon** [comment] 2023-06-04 07:13
Other possible mod incompatibles that may affected crash:

https://legacy.curseforge.com/minecraft/mc-mods/tiered-forge

**Comment by Cixon** [comment] 2023-06-04 07:57
It appears this issue is caused by the bleeding affect. Is there a way to disable the bleeding mechanic of your mod all together to avoid this issue?

**Comment by Majrusz** [comment] 2023-06-04 08:28
Hi, thanks for the report. Yes, there is a config to disable Bleeding completely, but I will still try to fix it

**Comment by Majrusz** [comment] 2023-06-04 08:46
Unfortunately, I am not able to reproduce this bug/crash using:
- tiered-1.18.2-4.1.2
- untamedwilds-1.18.2-2.4.0
- majrusz-library-1.18.2-4.2.0
- majruszs-difficulty-1.18.2-1.7.5
- unionlib-1.18.2-7.2.3
- citadel-1.11.3-1.18.2

Everything works fine on server-side and client-side even if spawn a lot of lions and other mobs

**Comment by Cixon** [comment] 2023-06-04 09:38
no worries, can i use the config folder to disable or does it need to be through the world folder? i don’t necessarily like the world folder since i’m in the process of finalizing a modpack, it wouldn’t be useful

**Comment by Majrusz** [comment] 2023-06-04 10:39
You can use `defaultconfigs` folder, it automatically adds configs from that folder to newly created worlds

**Comment by Cixon** [comment] 2023-06-04 23:26
Well now I'm confused because I disabled your bleeding mechanics via default configs and it fixed the initial error but switching to survival mode and eating cooked_steak on off-hand, killed client?

Mods in use:
https://legacy.curseforge.com/minecraft/mc-mods/atlas-combat - v1.1.5
https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks -v1.0.1
https://legacy.curseforge.com/minecraft/mc-mods/tiered-forge -v4.1.2

Logs:
[debug.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/11647449/debug.log)
[latest.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/11647450/latest.log)

Crash:
[crash-2023-06-04_18.19.49-client.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/11647452/crash-2023-06-04_18.19.49-client.txt)

**Comment by Cixon** [comment] 2023-06-04 23:33
for the record I am using ice and fire's recent 1.18.2 update as well but I didn't list it because I wasn't using any items from their mod for this testing.

**Comment by Majrusz** [comment] 2023-06-10 13:22
Okay, it should be fixed by now. Check the latest 4.3.1 library version and feel free to reopen the thread if the issue still occurs

**Closed as completed by Majrusz** 2023-06-10 13:22 UTC
Labels: bug, compatibility, 1.18.X, 1.19.X
