### ISSUE TITLE
way to disable world gen?

### ISSUE THREAD

**Issue by PabloDnSS** [Majrusz/MajruszsProgressiveDifficultyMod#215] opened 2024-02-28 15:37 UTC
awesome mod any way to disable world gen and get rif of enderium and end stone as well?

**Comment by Majrusz** [comment] 2024-03-02 09:53
Hello, at the moment it is not possible unfortunately

**Comment by Majrusz** [comment] 2024-03-02 11:09
Duplicate of https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/112

**Closed as not planned by Majrusz** 2024-03-02 11:09 UTC
Labels: enhancement, 1.20.X

**Comment by wilsoffer** [comment] 2024-06-18 18:30
Use the BlockSwap mod to remove world generation. There are numerous tutorials online
